// constants.ts
import { UnitTypeData } from './types';

export const PIECES: { [key: string]: UnitTypeData } = {
  farmer: {
    id: 'farmer',
    name: 'Farmer',
    color: '#8B4513',
    tier: 0,
    evolvesFromUnitId: null,
    evolvesToUnitId: 'serf',
    baseStats: {
      level: 1,
      experience: 0,
      maxExperience: 100,
      hitpoints: 250,
      strength: 10,
      dexterity: 8,
      intelligence: 5,
    },
    clearedCount: 0,
    combatDeaths: 0,
  },
  scholar: {
    id: 'scholar',
    name: 'Scholar',
    color: '#4169E1',
    tier: 0,
    evolvesFromUnitId: null,
    evolvesToUnitId: 'mage',
    baseStats: {
      level: 1,
      experience: 0,
      maxExperience: 100,
      hitpoints: 200,
      strength: 5,
      dexterity: 10,
      intelligence: 15,
    },
    clearedCount: 0,
    combatDeaths: 0,
  },
  rogue: {
    id: 'rogue',
    name: 'Rogue',
    color: '#2F4F4F',
    tier: 0,
    evolvesFromUnitId: null,
    evolvesToUnitId: 'marksman',
    baseStats: {
      level: 1,
      experience: 0,
      maxExperience: 100,
      hitpoints: 220,
      strength: 8,
      dexterity: 15,
      intelligence: 8,
    },
    clearedCount: 0,
    combatDeaths: 0,
  },
  serf: {
    id: 'serf',
    name: 'Serf',
    color: '#CD853F',
    tier: 1,
    evolvesFromUnitId: 'farmer',
    evolvesToUnitId: 'tbd',
    baseStats: {
      level: 1,
      experience: 0,
      maxExperience: 150,
      hitpoints: 500,
      strength: 20,
      dexterity: 16,
      intelligence: 10,
    },
    clearedCount: 0,
    combatDeaths: 0,
  },
  mage: {
    id: 'mage',
    name: 'Mage',
    color: '#9370DB',
    tier: 1,
    evolvesFromUnitId: 'scholar',
    evolvesToUnitId: 'tbd',
    baseStats: {
      level: 1,
      experience: 0,
      maxExperience: 150,
      hitpoints: 400,
      strength: 10,
      dexterity: 20,
      intelligence: 30,
    },
    clearedCount: 0,
    combatDeaths: 0,
  },
  marksman: {
    id: 'marksman',
    name: 'Marksman',
    color: '#556B2F',
    tier: 1,
    evolvesFromUnitId: 'rogue',
    evolvesToUnitId: 'tbd',
    baseStats: {
      level: 1,
      experience: 0,
      maxExperience: 150,
      hitpoints: 440,
      strength: 16,
      dexterity: 30,
      intelligence: 16,
    },
    clearedCount: 0,
    combatDeaths: 0,
  },
};

export const GAME_DEFAULTS = {
  ACTIVE_PIECES: ['farmer', 'scholar', 'rogue'],
  
  // Grid and visual constants
  CELL_SIZE: 1,
  CELL_GAP: 0.05,
  
  // Animation speed constants
  DROP_SPEED: 20,
  SHRINK_DURATION: 2,
  MATCH_CLEAR_DURATION: 0.5,
  GRAVITY_SPEED: 10,
  FORMATION_SPEED: 5,
  SCORE_POPUP_DURATION: 2,
  SCORE_FLOAT_SPEED: 12,
  SCORE_SCALE_SPEED: 0.3,
  SCORE_FADE_START: 0.7,
  SHAPE_HEIGHT: 2,
  GRID_COLS: 6,
  GRID_ROWS: 6,
  CURSOR_ROW: 0,
  ROTATION: 0,
  SWAP_RADIUS: 1,
  MAX_MOVEMENTS: 10,
  MAX_SWAPS: 5,
  MIN_MATCH_COUNT: 3,
  ENABLE_MATCH_LOGIC: true,
  MATCH_EFFECT: 'clear' as 'clear' | 'merge',
  COMBAT_TIMER: 10,
  COMBAT_TIMER_MAX: 10,
  CASUALTY_PERCENTAGE: 20,
  PIECE_CLEAR_VALUE: 100,
  BASE_SCALAR: 10,
  MERGE_Y_PRIORITY: 'low' as 'low' | 'high',
  MERGE_X_PRIORITY: 'left' as 'left' | 'right',
  MERGE_XY_PRIORITY: 'x' as 'x' | 'y',
  FORMATION_DIRECTION: 'right' as 'left' | 'right' | 'up' | 'down',
};
export const STYLES = {
  panel: { background: 'rgba(0,0,0,0.8)', padding: '15px', borderRadius: '8px' },
  debugInput: { width: '50px', padding: '4px', fontSize: '12px', color: '#000', background: '#fff' },
  debugLabel: { fontSize: '12px', width: '90px' },
  inputRow: { display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '8px' },
  section: { marginTop: '15px', paddingTop: '15px', borderTop: '1px solid #666' },
};